name: build
on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker compose build
      - name: Clean Env
        if: always()
        run: docker system prune --volumes -af
