name: dev_deploy
on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted, parallel]
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.UWPATH_DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.UWPATH_DOCKER_PASSWORD }}
      run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - name: Build Image
      run: |
          docker compose build
          docker image ls
    - name: Push to Registry
      run: |
          docker tag $(docker images uwpath_frontend --format "{{.ID}}") uwpathdocker/uwpath_frontend:int
          docker push uwpathdocker/uwpath_frontend:int
    - name: Clean Env
      if: always()
      run: |
        docker system prune --volumes -af
        docker logout
